#!/usr/bin/env python3

SHARD_COUNT = 1
OWNER_ID = 600913266394529813 # Your Discord ID

TICKER = 'ETH'
CONVERT = 'USD'
CONVERT_SYMBOL = '$'

DISCORD_TOKEN = 'YOUR_DISCORD_BOT_TOKEN'
API_KEY = 'YOUR_CRYPTO_COMPARE_API_KEY'